name: Linting

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: npm install -g pnpm@11.9.0 && pnpm install

            - name: Build packages
              run: pnpm --filter "./packages/*" build

            - name: Run Lint
              run: pnpm lint
